---
title: "Gov 50 Final Project"
author: Paige Breyer
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Milestone 1

I am interested in exploring data related to...
criminal justice. Specifically, I hope to look at data from states with the death penalty and those without to see whether or not capital punishment lowers crime rates. I am interested in learning how to create an accurate data set for this project, given that controlled experiments are more difficult in the social sciences. 

## Data Loading 

```{r}
hate_crimes
```

## Milestone 2

My research question for the final project is: do areas with a higher level of economic inequality experience more hate crimes? Before examining the evidence, I hypothesize that areas with more economic inequality will have a higher level of hate crimes due to the tension between communities that is often exacerbated by poverty. Individuals living in areas where financial hardship is more common are presumably more likely to feel animosity toward other groups of people, as competition for scarce resources is more acute. 



